node {
    stage 'Checkout' 
        checkout scm 
    
    stage 'Build' 
        bat 'mvn install -DskipTests=true Dmaven.javadoc.skip=true -B -V' 
    if(projectSettings.HasTests())
    {
    stage 'Test' 
        bat 'mvn test' 
    }
}